-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- vim.api.nvim_create_autocmd("CmdlineEnter", {
--   pattern = "*",
--   callback = function()
--     -- require("lualine").hide({})
--     vim.cmd("highlight MsgArea guibg=none guifg=#B48EAD gui=bold guisp=NONE")
--   end,
-- })
